model:
  _target_: src.model.kan.kan.KAN
  G: 5
  k: 3
  width: [2, 5, 1]
  default_grid_range: [-1, 1]
  b: SiLU
  threshold: 5e-2

optimizer:
  is_lbfgs: True
  lr: 1

loss:
  loss_func: "MSE"
  lamb: 0.
  lamb_l1: 1
  lamb_entropy: 2
  lamb_l1_coef: 0.
  lamb_l1_coef_diff: 0.